name: citation
channels:
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.2.1
  - numpy=1.26.0
  - cudnn=8.9.2.26
  - pip:
    - accelerate==0.23.0
    - datasets==2.14.5
    - deepspeed==0.12.2
    # - flash-attn==2.3.0 : install with uv pip install flash-attn==2.3.0 
    - httpx==0.25.0
    - huggingface-hub==0.24.0
    - ipython==8.16.1
    - jieba==0.42.1
    - jinja2==3.1.2
    - langchain==0.2.11
    - langchain-community==0.2.10
    - langchain-core==0.2.23
    - langchain-experimental==0.0.63
    - langchain-huggingface==0.0.3
    - langchain-text-splitters==0.2.2
    - langsmith==0.1.93
    - matplotlib==3.8.0
    - networkx==3.1
    - ninja==1.11.1
    - nltk==3.8.1
    - pandas==2.1.1
    - packaging==24.1
    - scikit-learn==1.3.1
    - scipy==1.11.2
    - tokenizers==0.19.1
    # - torch==2.0.1 : install with uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
    - tqdm==4.66.1
    - trl==0.7.1
